# -*- coding: utf-8 -*-
"""requirment.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVaWs5a-_n7QaCkzjeKL9Runa5WAN5Z5
"""

fastapi
uvicorn
pandas
numpy
scikit-learn
tensorflow
transformers
joblib
pillow
pytesseract
requests
python-multipart